apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-resource-advisor
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: k8s-resource-advisor
      restartPolicy: Never
      containers:
      - name: k8s-resource-advisor
        image: ghcr.io/pala3232/k8s-resource-advisor:latest
        command: ["k8s-advisor"]
        env:
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: k8s-advisor-secrets
              key: SLACK_WEBHOOK_URL
              optional: true
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
